### ISSUE TITLE
When I switch on focus-mode, my C-x f and ido-switch-buffer change

### ISSUE THREAD

**Issue by kootenpv** [larstvei/Focus#8] opened 2016-10-13 20:40 UTC
Very absurd, but somehow after loading focus-mode, it changes these settings to use Recentf rather than find file or switch buffer?!

**Comment by larstvei** [comment] 2016-10-16 16:02
This sounds very strange, as `focus-mode` does not change any variables other than those defined in `focus.el` and `cursor-type` which seems completely unrelated.

It would be great if you could provide a more detailed explanation of what happens. If you can provide a minimal example of the bug, that would be great. If not, could you provide a link to your configuration file?

**Comment by kootenpv** [comment] 2016-10-16 16:39
Even my `M-x` changes. My configuration is not completely public unfortunately, though the structure is very similar to https://github.com/kootenpv/emp. 

A clean emacs startup + starting `focus-mode` already causes it, so I'm sure it is focus related. I haven't seen this behavior with any other package.

I'm sorry for not being able to provide a reproducible case or have any clue how it might be related, but maybe "the next person" with some issues could append.

**Comment by larstvei** [comment] 2016-10-16 17:56
I was not able to reproduce the issue using the `emp` config you provided. It did however yield a compilation error when I installed it:

```
focus.el:204:9:Error: ‘recenter’ing a window that does not display current-buffer.
```

This is not a `focus` error.

Generally, if a bug cannot be produced with `emacs -q` (i.e. not loading a configuration file), then it is not really a package bug. Of course, if the package interferes with some common packages (e.g `ido-mode`) this should be fixed.

My best guess is that your config includes some advice, hook or redefines some function which does not play nice with focus mode. If you can provide some more information I'd be happy to try to fix this, but so far I have not found anything indicating that focus interferes with any commonly used package.

I'll close this, seeing that it is not reproducible using `emacs -q`. If you, or someone else, can give some reproducible example then the issue can of course be reopened :)

**Closed by larstvei** 2016-10-16 17:56 UTC
