### ISSUE TITLE
It only works in soft-wrapped text

### ISSUE THREAD

**Issue by mrbig033** [larstvei/Focus#17] opened 2018-07-10 09:14 UTC
I have the habit of formatting my text on Evil mode using the command "gwap" (evil-fill), and Focus does not recognize these paragraphs, even though there are blank lines between them.

**Comment by larstvei** [comment] 2018-07-12 02:33
Hi!

Can you provide an example? Does it work if you use Emacs' built-in `fill-paragraph`?

I doubt that Evil mode has anything to do with it, as Focus only cares about the text around the cursor.

**Comment by larstvei** [comment] 2019-03-09 17:24
Closing because I can't reproduce.

**Closed by larstvei** 2019-03-09 17:24 UTC
